---
- name: install cache node
  hosts: cashe-node
  become: true
  become_method: sudo
 
  tasks: 
   - name: install nginx
     shell: |
       sudo apt-get update
       sudo apt-get install nginx -y
       exit 0     
   - copy:
     src: /srv/myfiles/foo.conf
     dest: /etc/foo.conf
     owner: foo
     group: foo
     mode: 0644   
   - name: restart nginx
     shell: |
       sudo service nginx restart
       exit 0  

